### ISSUE TITLE
A question when i run train.py

### ISSUE THREAD

**Issue by xing3507** [Song-Jingyu/PointPainting#16]
when i run     python train.py --cfg_file cfgs/kitti_models/pointpillar_painted.yaml

it says that :

Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 112, in main
    total_epochs=args.epochs
  File "/media/user/date/ZXH/PointPainting-main/detector/tools/pcdet/datasets/__init__.py", line 46, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
KeyError: 'PaintedKittiDataset'

How can i fix it?? @Song-Jingyu  谢谢！！！

**Comment by Song-Jingyu** [comment]
I am not sure why this happen. But I would suggest remove and uninstall and re-download this repo to see if this would help.
