### ISSUE TITLE
No module named 'pcdet.version' & KeyError: 'PaintedKittiDataset

### ISSUE THREAD

**Issue by shadismz** [Song-Jingyu/PointPainting#26]
Hello,
while running this part of the code

$ cd detector
$ python -m pcdet.datasets.kitti.painted_kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/painted_kitti_dataset.yaml
$ cd tools
$ python train.py --cfg_file cfgs/kitti_models/pointpillar_painted.yaml

I ran to this error

/content/PointPainting/detector
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/content/PointPainting/detector/pcdet/__init__.py", line 4, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'pcdet.version'
/content/PointPainting/detector/tools
2022-08-11 10:36:39,752   INFO  **********************Start logging**********************
2022-08-11 10:36:39,753   INFO  CUDA_VISIBLE_DEVICES=ALL
2022-08-11 10:36:39,753   INFO  cfg_file         cfgs/kitti_models/pointpillar_painted.yaml
2022-08-11 10:36:39,753   INFO  batch_size       4
2022-08-11 10:36:39,753   INFO  epochs           80
2022-08-11 10:36:39,753   INFO  workers          8
2022-08-11 10:36:39,753   INFO  extra_tag        default
2022-08-11 10:36:39,753   INFO  ckpt             None
2022-08-11 10:36:39,753   INFO  pretrained_model None
2022-08-11 10:36:39,753   INFO  launcher         none
2022-08-11 10:36:39,753   INFO  tcp_port         18888
2022-08-11 10:36:39,753   INFO  sync_bn          False
2022-08-11 10:36:39,753   INFO  fix_random_seed  False
2022-08-11 10:36:39,753   INFO  ckpt_save_interval 1
2022-08-11 10:36:39,753   INFO  local_rank       0
2022-08-11 10:36:39,753   INFO  max_ckpt_save_num 30
2022-08-11 10:36:39,754   INFO  merge_all_iters_to_one_epoch False
2022-08-11 10:36:39,754   INFO  set_cfgs         None
2022-08-11 10:36:39,754   INFO  max_waiting_mins 0
2022-08-11 10:36:39,754   INFO  start_epoch      0
2022-08-11 10:36:39,754   INFO  save_to_file     False
2022-08-11 10:36:39,754   INFO  cfg.ROOT_DIR: /content/OpenPCDet
2022-08-11 10:36:39,754   INFO  cfg.LOCAL_RANK: 0
2022-08-11 10:36:39,754   INFO  cfg.CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']
2022-08-11 10:36:39,754   INFO  
cfg.DATA_CONFIG = edict()
2022-08-11 10:36:39,754   INFO  cfg.DATA_CONFIG.DATASET: PaintedKittiDataset
2022-08-11 10:36:39,754   INFO  cfg.DATA_CONFIG.DATA_PATH: ../data/kitti
2022-08-11 10:36:39,754   INFO  cfg.DATA_CONFIG.POINT_CLOUD_RANGE: [0, -39.68, -3, 69.12, 39.68, 1]
2022-08-11 10:36:39,754   INFO  
cfg.DATA_CONFIG.DATA_SPLIT = edict()
2022-08-11 10:36:39,754   INFO  cfg.DATA_CONFIG.DATA_SPLIT.train: train
2022-08-11 10:36:39,754   INFO  cfg.DATA_CONFIG.DATA_SPLIT.test: val
2022-08-11 10:36:39,754   INFO  
cfg.DATA_CONFIG.INFO_PATH = edict()
2022-08-11 10:36:39,755   INFO  cfg.DATA_CONFIG.INFO_PATH.train: ['kitti_infos_train.pkl']
2022-08-11 10:36:39,755   INFO  cfg.DATA_CONFIG.INFO_PATH.test: ['kitti_infos_val.pkl']
2022-08-11 10:36:39,755   INFO  cfg.DATA_CONFIG.FOV_POINTS_ONLY: True
2022-08-11 10:36:39,755   INFO  
cfg.DATA_CONFIG.DATA_AUGMENTOR = edict()
2022-08-11 10:36:39,755   INFO  cfg.DATA_CONFIG.DATA_AUGMENTOR.DISABLE_AUG_LIST: ['placeholder']
2022-08-11 10:36:39,755   INFO  cfg.DATA_CONFIG.DATA_AUGMENTOR.AUG_CONFIG_LIST: [{'NAME': 'gt_sampling', 'USE_ROAD_PLANE': True, 'DB_INFO_PATH': ['kitti_dbinfos_train.pkl'], 'PREPARE': {'filter_by_min_points': ['Car:5', 'Pedestrian:5', 'Cyclist:5'], 'filter_by_difficulty': [-1]}, 'SAMPLE_GROUPS': ['Car:15', 'Pedestrian:15', 'Cyclist:15'], 'NUM_POINT_FEATURES': 8, 'DATABASE_WITH_FAKELIDAR': False, 'REMOVE_EXTRA_WIDTH': [0.0, 0.0, 0.0], 'LIMIT_WHOLE_SCENE': False}, {'NAME': 'random_world_flip', 'ALONG_AXIS_LIST': ['x']}, {'NAME': 'random_world_rotation', 'WORLD_ROT_ANGLE': [-0.78539816, 0.78539816]}, {'NAME': 'random_world_scaling', 'WORLD_SCALE_RANGE': [0.95, 1.05]}]
2022-08-11 10:36:39,755   INFO  
cfg.DATA_CONFIG.POINT_FEATURE_ENCODING = edict()
2022-08-11 10:36:39,755   INFO  cfg.DATA_CONFIG.POINT_FEATURE_ENCODING.encoding_type: absolute_coordinates_encoding
2022-08-11 10:36:39,755   INFO  cfg.DATA_CONFIG.POINT_FEATURE_ENCODING.used_feature_list: ['x', 'y', 'z', 'intensity', 's0', 's1', 's2', 's3']
2022-08-11 10:36:39,755   INFO  cfg.DATA_CONFIG.POINT_FEATURE_ENCODING.src_feature_list: ['x', 'y', 'z', 'intensity', 's0', 's1', 's2', 's3']
2022-08-11 10:36:39,755   INFO  cfg.DATA_CONFIG.DATA_PROCESSOR: [{'NAME': 'mask_points_and_boxes_outside_range', 'REMOVE_OUTSIDE_BOXES': True}, {'NAME': 'shuffle_points', 'SHUFFLE_ENABLED': {'train': True, 'test': False}}, {'NAME': 'transform_points_to_voxels', 'VOXEL_SIZE': [0.16, 0.16, 4], 'MAX_POINTS_PER_VOXEL': 32, 'MAX_NUMBER_OF_VOXELS': {'train': 16000, 'test': 40000}}]
2022-08-11 10:36:39,755   INFO  cfg.DATA_CONFIG._BASE_CONFIG_: cfgs/dataset_configs/painted_kitti_dataset.yaml
2022-08-11 10:36:39,755   INFO  
cfg.MODEL = edict()
2022-08-11 10:36:39,755   INFO  cfg.MODEL.NAME: PointPillar
2022-08-11 10:36:39,755   INFO  
cfg.MODEL.VFE = edict()
2022-08-11 10:36:39,755   INFO  cfg.MODEL.VFE.NAME: PillarVFE
2022-08-11 10:36:39,755   INFO  cfg.MODEL.VFE.WITH_DISTANCE: False
2022-08-11 10:36:39,756   INFO  cfg.MODEL.VFE.USE_ABSLOTE_XYZ: True
2022-08-11 10:36:39,756   INFO  cfg.MODEL.VFE.USE_NORM: True
2022-08-11 10:36:39,756   INFO  cfg.MODEL.VFE.NUM_FILTERS: [64]
2022-08-11 10:36:39,756   INFO  
cfg.MODEL.MAP_TO_BEV = edict()
2022-08-11 10:36:39,756   INFO  cfg.MODEL.MAP_TO_BEV.NAME: PointPillarScatter
2022-08-11 10:36:39,756   INFO  cfg.MODEL.MAP_TO_BEV.NUM_BEV_FEATURES: 64
2022-08-11 10:36:39,756   INFO  
cfg.MODEL.BACKBONE_2D = edict()
2022-08-11 10:36:39,756   INFO  cfg.MODEL.BACKBONE_2D.NAME: BaseBEVBackbone
2022-08-11 10:36:39,756   INFO  cfg.MODEL.BACKBONE_2D.LAYER_NUMS: [3, 5, 5]
2022-08-11 10:36:39,756   INFO  cfg.MODEL.BACKBONE_2D.LAYER_STRIDES: [2, 2, 2]
2022-08-11 10:36:39,756   INFO  cfg.MODEL.BACKBONE_2D.NUM_FILTERS: [64, 128, 256]
2022-08-11 10:36:39,756   INFO  cfg.MODEL.BACKBONE_2D.UPSAMPLE_STRIDES: [1, 2, 4]
2022-08-11 10:36:39,756   INFO  cfg.MODEL.BACKBONE_2D.NUM_UPSAMPLE_FILTERS: [128, 128, 128]
2022-08-11 10:36:39,756   INFO  
cfg.MODEL.DENSE_HEAD = edict()
2022-08-11 10:36:39,756   INFO  cfg.MODEL.DENSE_HEAD.NAME: AnchorHeadSingle
2022-08-11 10:36:39,756   INFO  cfg.MODEL.DENSE_HEAD.CLASS_AGNOSTIC: False
2022-08-11 10:36:39,756   INFO  cfg.MODEL.DENSE_HEAD.USE_DIRECTION_CLASSIFIER: True
2022-08-11 10:36:39,756   INFO  cfg.MODEL.DENSE_HEAD.DIR_OFFSET: 0.78539
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.DIR_LIMIT_OFFSET: 0.0
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.NUM_DIR_BINS: 2
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.ANCHOR_GENERATOR_CONFIG: [{'class_name': 'Car', 'anchor_sizes': [[3.9, 1.6, 1.56]], 'anchor_rotations': [0, 1.57], 'anchor_bottom_heights': [-1.78], 'align_center': False, 'feature_map_stride': 2, 'matched_threshold': 0.6, 'unmatched_threshold': 0.45}, {'class_name': 'Pedestrian', 'anchor_sizes': [[0.8, 0.6, 1.73]], 'anchor_rotations': [0, 1.57], 'anchor_bottom_heights': [-0.6], 'align_center': False, 'feature_map_stride': 2, 'matched_threshold': 0.5, 'unmatched_threshold': 0.35}, {'class_name': 'Cyclist', 'anchor_sizes': [[1.76, 0.6, 1.73]], 'anchor_rotations': [0, 1.57], 'anchor_bottom_heights': [-0.6], 'align_center': False, 'feature_map_stride': 2, 'matched_threshold': 0.5, 'unmatched_threshold': 0.35}]
2022-08-11 10:36:39,757   INFO  
cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG = edict()
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.NAME: AxisAlignedTargetAssigner
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.POS_FRACTION: -1.0
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.SAMPLE_SIZE: 512
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.NORM_BY_NUM_EXAMPLES: False
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.MATCH_HEIGHT: False
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.BOX_CODER: ResidualCoder
2022-08-11 10:36:39,757   INFO  
cfg.MODEL.DENSE_HEAD.LOSS_CONFIG = edict()
2022-08-11 10:36:39,757   INFO  
cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS = edict()
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.cls_weight: 1.0
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.loc_weight: 2.0
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.dir_weight: 0.2
2022-08-11 10:36:39,757   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
2022-08-11 10:36:39,758   INFO  
cfg.MODEL.POST_PROCESSING = edict()
2022-08-11 10:36:39,758   INFO  cfg.MODEL.POST_PROCESSING.RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
2022-08-11 10:36:39,758   INFO  cfg.MODEL.POST_PROCESSING.SCORE_THRESH: 0.1
2022-08-11 10:36:39,758   INFO  cfg.MODEL.POST_PROCESSING.OUTPUT_RAW_SCORE: False
2022-08-11 10:36:39,758   INFO  cfg.MODEL.POST_PROCESSING.EVAL_METRIC: kitti
2022-08-11 10:36:39,758   INFO  
cfg.MODEL.POST_PROCESSING.NMS_CONFIG = edict()
2022-08-11 10:36:39,758   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.MULTI_CLASSES_NMS: False
2022-08-11 10:36:39,758   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_TYPE: nms_gpu
2022-08-11 10:36:39,758   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_THRESH: 0.01
2022-08-11 10:36:39,758   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_PRE_MAXSIZE: 4096
2022-08-11 10:36:39,758   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_POST_MAXSIZE: 500
2022-08-11 10:36:39,758   INFO  
cfg.OPTIMIZATION = edict()
2022-08-11 10:36:39,758   INFO  cfg.OPTIMIZATION.BATCH_SIZE_PER_GPU: 4
2022-08-11 10:36:39,758   INFO  cfg.OPTIMIZATION.NUM_EPOCHS: 80
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.OPTIMIZER: adam_onecycle
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.LR: 0.003
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.WEIGHT_DECAY: 0.01
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.MOMENTUM: 0.9
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.MOMS: [0.95, 0.85]
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.PCT_START: 0.4
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.DIV_FACTOR: 10
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.DECAY_STEP_LIST: [35, 45]
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.LR_DECAY: 0.1
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.LR_CLIP: 1e-07
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.LR_WARMUP: False
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.WARMUP_EPOCH: 1
2022-08-11 10:36:39,759   INFO  cfg.OPTIMIZATION.GRAD_NORM_CLIP: 10
2022-08-11 10:36:39,759   INFO  cfg.TAG: pointpillar_painted
2022-08-11 10:36:39,759   INFO  cfg.EXP_GROUP_PATH: kitti_models
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 112, in main
    total_epochs=args.epochs
  File "/content/OpenPCDet/pcdet/datasets/__init__.py", line 51, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
KeyError: 'PaintedKittiDataset'

I searched, but I couldn't find something usefull!
Do you have any idea?

**Comment by shadismz** [comment]
I used the  modified version of pcdet provided in ./detector and the problem was solved.
